### ISSUE TITLE
Consider about adding back in Mercator projection

### ISSUE THREAD

**Issue by thareUSGS** [pole-surfaces-planetaires/csvforwkt#4]
The Mercator projection historically was a popular projection for planetary maps. There is some interest in re-listing Mercator as an option since it has been recently widely used in web maps.  Original [2000 codes listed](https://www.lpi.usra.edu/meetings/lpsc2006/pdf/1931.pdf) it as XXX74 (e.g., 49974), defaulting to center meridian = 0.

Perhaps wait until next IAU report (ETA -- soon-ish) to add this in -- even if an addition should be backwards compatible.

**Comment by AndrewAnnex** [comment]
@thareUSGS and @J-Christophe take a look at #5 as I'd like to not have to wait for the next IAU report, I've also made https://github.com/OSGeo/PROJ/pull/3645 to patch things on PROJ

**Comment by AndrewAnnex** [comment]
#5 addresses this issue for this repo

**Comment by thareUSGS** [comment]
@AndrewAnnex for global maps (and planetary), I generally like to at least have clon=0 AND a clon=180 for those who want a more 0 to 360 data set. However, since this is really to fit into existing applications/services, do you ever see those being able to support clon=180. Basically should we add a code "91" to be clon=180?

**Comment by AndrewAnnex** [comment]
@thareUSGS I could add that but I think the code would have to be "95" to follow the standard used elsewhere here, a bigger question is if psuedomercator even allows for the idea of a anti-meridian centered mercator projection. I don't think many tools even respect the clon=180 for the equirectangular case as-is though so hopefully this isn't a blocker issue for you and this pr

**Comment by thareUSGS** [comment]
Good catch, yes if would be 95. I am tempted to leave it out for now since this is for matching existing services.
